server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  application:
      name: hotelmaster
  datasource:
    url: "jdbc:mysql://localhost:3366/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
       ddl-auto: update
    show_sql: true

